### ISSUE TITLE
Add Documentation and Implement Previous Iterator

### ISSUE THREAD

**Issue by appcypher** [WebNativeFileSystem/rs-skip-ratchet#1]
As discussed. I'm leaving this issue here as a reference point.

### Todo
- [x] Add documentation to API 
- [x] Implement Iterator design pattern for revision history
- [x] Make code more idiomatic
- [x] Add structure to code
